name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.IP }}
          username: ${{ vars.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/GeoTasker
            git pull origin main
            npm ci
            npm run build
            npx pm2 startOrRestart ecosystem.config.cjs --env production
